package platform.game.level;

import platform.game.World;

import platform.game.Xor;
import platform.game.Actor;
import platform.game.And;
import platform.game.Background;
import platform.game.Block;
import platform.game.Bow;
import platform.game.Button;
import platform.game.Colors;
import platform.game.Door;
import platform.game.DynamicBackground;
import platform.game.Exit;
import platform.game.Heart;
import platform.game.Jumper;
import platform.game.Key;
import platform.game.Led;
import platform.game.Lever;
import platform.game.Limits;
import platform.game.Mover;
import platform.game.Not;
import platform.game.Oscillator;
import platform.game.Overlay;
import platform.game.Particle;
import platform.game.Player;
import platform.game.Sign;
import platform.game.Spike;
import platform.game.Switch;
import platform.game.Torch;
import platform.util.Box;
import platform.util.Vector;

public class Level1 extends Level 
{
	public void register(World world)
	{
		super.register(world);
		
		Player player1 = new Player(new Vector(-13,-2), new Vector(0,0)) ;
        world.register(player1) ;
		Overlay over1 = new Overlay(player1) ;
		world.register(over1);
		world.register(new Sign(new Vector(-12, -2), world.getLoader().getSprite("level.1")));
		world.register(new Block(new Box(new Vector(-15,-4), new Vector(-10,-2)), world.getLoader().getSprite("castle.left")));
		world.register(new Block(new Box(new Vector(-10,-4), new Vector(-5,-2)), world.getLoader().getSprite("castle.middle")));
		world.register(new Block(new Box(new Vector(-5,-4), new Vector(0,-2)), world.getLoader().getSprite("castle.middle")));
		world.register(new Block(new Box(new Vector(0,-4), new Vector(5,-2)), world.getLoader().getSprite("castle.middle")));
		world.register(new Block(new Box(new Vector(5,-4), new Vector(10,-2)), world.getLoader().getSprite("castle.right")));
		world.register(new Block(new Box(new Vector(-17,-4), new Vector(-15,4)), world.getLoader().getSprite("stone.7")));
		world.register(new Block(new Box(new Vector(-15,-2), new Vector(-14,6)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Block(new Box(new Vector(-15,6), new Vector(-14,14)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Block(new Box(new Vector(4,-2), new Vector(5,6)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Block(new Box(new Vector(4,6), new Vector(5,14)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Block(new Box(new Vector(-14,1), new Vector(-9,2)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-9,1), new Vector(-4,2)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-4,1), new Vector(1,2)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(3,1), new Vector(4,5)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Spike(new Vector(-11,-2)));
		world.register(new Spike(new Vector(-10,-2)));
		world.register(new Spike(new Vector(-9,-2)));
		world.register(new Spike(new Vector(-8,-2)));
		world.register(new Spike(new Vector(-5,-2)));
		world.register(new Spike(new Vector(-4,-2)));
		world.register(new Spike(new Vector(-3,-2)));
		world.register(new Spike(new Vector(-2,-2)));
		world.register(new Spike(new Vector(0,-2)));
		world.register(new Jumper(new Vector(2,-2)));
		world.register(new Bow(2,1,new Vector(3.5,1)));
		world.register(new Block(new Box(new Vector(-1,5), new Vector(4,6)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-6,5), new Vector(-1,6)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-11,5), new Vector(-6,6)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-14,5), new Vector(-13,9)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Jumper(new Vector(-12,2)));
		world.register(new Bow(0,1,new Vector(-13.5,2)));
		Torch torch1 = new Torch(new Vector(-13.5,4.5), false) ;
		world.register(torch1);
		world.register(new Door(new Vector(-12.5,5.5), Colors.GREEN, torch1));
		world.register(new Door(new Vector(-11.5,5.5), Colors.GREEN, torch1));
		world.register(new Block(new Box(new Vector(-14,9), new Vector(-9,10)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-9,9), new Vector(-4,10)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(-4,9), new Vector(1,10)), world.getLoader().getSprite("stone.broken.3")));
		world.register(new Block(new Box(new Vector(3,9), new Vector(4,14)), world.getLoader().getSprite("stone.broken.7")));
		world.register(new Jumper(new Vector(2,6)));
		world.register(new Jumper(new Vector(-12,10)));
		Lever lever1 = new Lever(new Vector(-13.5,10), Double.POSITIVE_INFINITY) ;
		world.register(lever1);
		world.register(new Heart(new Vector(4.5,14)));
		Torch torch2 = new Torch(new Vector(4.5,16.5), false) ;
		world.register(torch2);
		world.register(new Jumper(new Vector(10,6)));
		world.register(new Jumper(new Vector(15,8)));
		world.register(new Block(new Box(new Vector(22,10), new Vector(27,11)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(27,10), new Vector(32,11)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(22,14), new Vector(27,15)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(27,14), new Vector(31,15)), world.getLoader().getSprite("stone.3")));
		Button button1 = new Button(new Vector(29,11.25)) ;
		world.register(button1);
		world.register(new Mover(new Box(new Vector(31,11), new Vector(32,15)), world.getLoader().getSprite("stone.broken.7"), button1, new Vector(31.5,17)));
		Lever lever2 = new Lever(new Vector(38.5,11), Double.POSITIVE_INFINITY) ;
		world.register(lever2);
		Oscillator oscillator1 = new Oscillator(4);
		world.register(oscillator1);
		world.register(new Led(new Box(new Vector(30,13), new Vector(31,14)), oscillator1));
		world.register(new Mover(new Box(new Vector(32,10), new Vector(35,11)), world.getLoader().getSprite("stone.broken.3"), new And(lever2,oscillator1), new Vector(33.5,8.5)));
		world.register(new Block(new Box(new Vector(35,10), new Vector(39,11)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(39,8), new Vector(40,10)), world.getLoader().getSprite("stone.7")));
		world.register(new Block(new Box(new Vector(22,7), new Vector(27,8)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(27,7), new Vector(32,8)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(21,8), new Vector(22,10)), world.getLoader().getSprite("stone.7")));
		world.register(new Block(new Box(new Vector(32,7), new Vector(36,8)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(36,7), new Vector(39,8)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(38,8), new Vector(39,9)), world.getLoader().getSprite("stone.1")));
		world.register(new Block(new Box(new Vector(22,8), new Vector(23,9)), world.getLoader().getSprite("stone.1")));
		world.register(new Heart(new Vector(23.5,8)));
		Key key1 = new Key(new Vector(22.5,9), Colors.RED) ;
		world.register(key1);
		world.register(new Bow(2,0.5,new Vector(38.5,9)));
		world.register(new Bow(2,0.5,new Vector(37.5,8)));
		world.register(new Block(new Box(new Vector(12,-7), new Vector(13,-2)), world.getLoader().getSprite("stone.7")));
		world.register(new Block(new Box(new Vector(7,-7), new Vector(12,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(2,-7), new Vector(7,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(0,-10), new Vector(2,-7)), world.getLoader().getSprite("stone.6")));
		world.register(new Block(new Box(new Vector(-5,-7), new Vector(0,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-12,-7), new Vector(-7,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-17,-7), new Vector(-12,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-22,-7), new Vector(-17,-6)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-5,-10), new Vector(0,-9)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-12,-10), new Vector(-7,-9)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-17,-10), new Vector(-12,-9)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-22,-10), new Vector(-17,-9)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-7,-10), new Vector(-6,-9)), world.getLoader().getSprite("stone.1")));
		world.register(new Block(new Box(new Vector(-6,-10), new Vector(-5,-9)), world.getLoader().getSprite("stone.1")));
		world.register(new Block(new Box(new Vector(-24,-10), new Vector(-22,-4)), world.getLoader().getSprite("stone.7")));
		world.register(new Block(new Box(new Vector(-24,-4), new Vector(-22,4)), world.getLoader().getSprite("stone.7")));
		Torch torch3 = new Torch(new Vector(-21,-2), false);
		world.register(torch3);
		Torch torch4 = new Torch(new Vector(-19.5,-2), false);
		world.register(torch4);
		Torch torch5 = new Torch(new Vector(-18,-2), false);
		world.register(torch5);
		Torch torch6 = new Torch(new Vector(-21,-0.5), false);
		world.register(torch6);
		Torch torch7 = new Torch(new Vector(-19.5,-0.5), false);
		world.register(torch7);
		Torch torch8 = new Torch(new Vector(-18,-0.5), false);
		world.register(torch8);
		Torch torch9 = new Torch(new Vector(-21,1), false);
		world.register(torch9);
		Torch torch10 = new Torch(new Vector(-19.5,1), false);
		world.register(torch10);
		Torch torch11 = new Torch(new Vector(-18,1), false);
		world.register(torch11);
		world.register(new Mover(new Box(new Vector(-22,-4), new Vector(-17,-3)), world.getLoader().getSprite("stone.3"),new And(torch3,new And(torch4,torch5)), new Vector(-19.5,30.5)));
		world.register(new Background(new Box(new Vector(-19.5,-3), 4,4), world.getLoader().getSprite("explosion")));
		world.register(new Block(new Box(new Vector(-17,30), new Vector(-12,31)), world.getLoader().getSprite("stone.3")));
		world.register(new Block(new Box(new Vector(-12,30), new Vector(-7,31)), world.getLoader().getSprite("stone.3")));
		Lever lever3 = new Lever(new Vector(-7.6,31), Double.POSITIVE_INFINITY);
		world.register(lever3);
		Key key2 = new Key(new Vector(-8.6, 31), Colors.YELLOW) ;
		world.register(key2);
		world.register(new Spike(new Vector(-16,31)));
		world.register(new Spike(new Vector(-15,31)));
		world.register(new Spike(new Vector(-14,31)));
		world.register(new Spike(new Vector(-13,31)));
		world.register(new Spike(new Vector(-11,31)));
		world.register(new Spike(new Vector(-10,31)));
		world.register(new Door(new Vector(4.5,-5.5), Colors.BLUE, new Not(lever3)));
		world.register(new Door(new Vector(4.5,-4.5), Colors.BLUE, new Not(lever3)));
		Oscillator oscillator2 = new Oscillator(1) ;
		world.register(oscillator2);
		world.register(new Door(new Vector(17,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(18,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(19,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Door(new Vector(20,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(21,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Door(new Vector(22,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(23,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Door(new Vector(24,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Door(new Vector(25,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(26,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(27,-2.5), Colors.BLUE, oscillator2));
		world.register(new Door(new Vector(28,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Door(new Vector(29,-2.5), Colors.GREEN, new Not(oscillator2)));
		world.register(new Block(new Box(new Vector(29.5,-3), new Vector(30.5,-2)), world.getLoader().getSprite("stone.1")));
		world.register(new Block(new Box(new Vector(30.5,-3), new Vector(31.5,-2)), world.getLoader().getSprite("stone.1")));
		Lever lever4 = new Lever(new Vector(31,-2), Double.POSITIVE_INFINITY) ;
		world.register(lever4);
		world.register(new Door(new Vector(-15.5,-8.5), Colors.RED, key1));
		world.register(new Door(new Vector(-15.5,-7.5), Colors.RED, key1));
		world.register(new Door(new Vector(-16.5,-8.5), Colors.YELLOW, key2));
		world.register(new Door(new Vector(-16.5,-7.5), Colors.YELLOW, key2));
		Lever lever5 = new Lever(new Vector(-0.6,-9), Double.POSITIVE_INFINITY);
		world.register(lever5);
		Lever lever6 = new Lever(new Vector(-21.4,-6), Double.POSITIVE_INFINITY) ;
		world.register(lever6);
		world.register(new Torch(new Vector(-21,-8), true));
		world.register(new Torch(new Vector(-18,-8), true));
		world.register(new Exit(new Vector(-19.5,-9), new Level2(), new And(lever5, new And(lever4, new And(lever1,lever6)))));
		world.register(new Limits(new Box(new Vector(-28,-15), new Vector(42,35))));
		world.register(new DynamicBackground(new Box(new Vector(-13,-2), 34, 17), world.getLoader().getSprite("background.2"), player1));
		
	}
}
